### ISSUE TITLE
"Persepolis" package does not run while the exact same version from aur works fine

### ISSUE THREAD

**Issue by barfin** [PedroHLC/chaotic-aur#33]
[barfin@ArchPC ~]$ persepolis 
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'persepolis==3.2.0' distribution was not found and is required by the application

**Comment by PedroHLC** [comment]
Sorry, this one wasn't rebuilt when python 3.8 arrived. But I did it now and it should be fine, you may need to trigger a reinstall.

**Comment by barfin** [comment]
> Sorry, this one wasn't rebuilt when python 3.8 arrived. But I did it now and it should be fine, you may need to trigger a reinstall.

i downloaded and installed it again but it gives the same error

**Comment by PedroHLC** [comment]
Sorry, my mistake, I rebuilt and removed the new build instead of the old.
This time I've tested it here and confirm that it's working.
If you need, feel free to reopen this issue.
:smile: Thanks for your contribution!
